server:
  port: 8080

spring:
  # 页面模板
  thymeleaf:
    # 不想每次修改页面都重启,改为false，默认true
    cache: false
    content-type: text/html
    # 编码格式
    encoding: UTF-8
    # 存放页面文件的目录
    prefix: classpath:/templates/views/
    # 页面文件后缀名
    suffix: .html
    # HTML5严格校验很烦人，改成LEGACYHTML5,默认为HTML5
    mode: HTML5





