
#server:
#  port: 8081
#  servlet:
#    encoding: UTF-8
#    enabled: true
#    force: true

spring:
#  cache.ehcache.config: classpath:ehcache-1.xml
  profiles:
#    include: db
    active: dev
#    2.4版本之后的写法
#    group:
#      "dev": "db"
#      "prod": "db"
#      "test": "db"

mybatis:
  mapper-locations: classpath:mapper/*.xml

book:
  date: 2021-3-31

swagger:
  ui-config:
    operations-sorter: method

logging:
  level:
    com.hl.chapter34.mapper: debug
  








